// import type { Metadata } from "next";
import "./globals.css";

import AuthProvider from "@/provider/AuthProvider";
import { QueryProvider } from "@/provider/QueryProvider";

import ClientLayout from "./client-layout";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout(
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>
) {
  
  const session = await getServerSession(authOptions);

  return (
    <AuthProvider session={session}>
      <QueryProvider>
        <ClientLayout>{children}</ClientLayout>
      </QueryProvider>
    </AuthProvider>
  );
}